### ISSUE TITLE
step 6. link not found

### ISSUE THREAD

**Issue by socar-mlb** [googlecodelabs/activity_transitionapi-codelab#1]
Activity Recognition Transition API Codelab
Step : 6. Review the Code 
<img width="609" alt="2018-06-07 1 00 14" src="https://user-images.githubusercontent.com/33410105/41077622-b665b852-6a52-11e8-96a8-5a995b35a6d7.png">

Link > Not Found

**Comment by gaeshi** [comment]
@socar-mlb the correct link is here:

https://github.com/googlecodelabs/activity_transitionapi-codelab/raw/master/BasicActivityTransitionsCodelab.zip

**Comment by codingjeremy** [comment]
I rewrote the codelab and fixed all links. PTAL and reopen if you see the same problem. Thanks!
