### ISSUE TITLE
The process to Remove updates when app is closing is duplicated in this Codelabs tutorial.

### ISSUE THREAD

**Issue by sourav-cc** [googlecodelabs/activity_transitionapi-codelab#12]
The process to remove updates when the app is closing is repeated along with the code to follow in step 6 (Setup activity transitions and request updates). 
I have added the link for reference here.[https://codelabs.developers.google.com/codelabs/activity-recognition-transition/index.html?index=..%2F..index#5](URL)

**Comment by codingjeremy** [comment]
Thanks for the catch! I removed it.

**Comment by sourav-cc** [comment]
Welcome!
