### ISSUE TITLE
Inconsistent performance on Samsung S9 phone running Android 10

### ISSUE THREAD

**Issue by Scott--R** [googlecodelabs/activity_transitionapi-codelab#14]
We compiled this example and it works well on a Google Pixel 2 running Android 11. We also integrated the activity transition API into our app and again, it works well on the Pixel 2. Then we started testing on a Samsung S9 and we are getting mixed results. As mentioned, we integrated the Activity Transition API into our app as well, and had both installed on the same phone for comparison. We also downloaded and installed other apps that utilize the Activity Transition API. We wanted to rule out any bugs in our code or possibly the demo code.

It was working fine for a while, then the API just suddenly stopped reporting activity transitions to all the apps. Our app creates a log for debugging and we can see our app suddenly just stops receiving activity transition updates. At the same time we checked the other apps and found the same result - all of them stopped receiving transition updates at the same time. Even after a full hard reboot of the Samsung phone, none of the apps were receiving transition updates anymore. Even tried uninstalling / reinstalling apps - no difference. All activity transitions stopped.

Then suddenly, they will start coming again. We do nothing different. All the apps registered for activity transitions suddenly started receiving them again. Then they will stop again as suddenly as they start.

We have tested with a few other phones and so far the Samsung S9+ is the only one doing this. There doesn't seem to be a pattern either. We can leave the phone sitting for hours, pick it up, and it works. We can do many transitions sequentially and it works. Then when it decides to stop working, we cannot get it working again even with a reboot. We just have to wait until it decides to work again.

Samsung Galaxy S9+
Android 10

**Comment by codingjeremy** [comment]
Thank you for this detailed testing!

This looks like more an issue with the device/api then with the sample itself.

Please report [here](https://source.android.com/setup/contribute/report-bugs). I might put it under the **System** category. Worse case, they will reroute it from there. 

Please include all this information and if this sample is used, feel free to send them your APK/point to this source.

Thanks!
