### ISSUE TITLE
Typo in Spet 4

### ISSUE THREAD

**Issue by lorduriel** [googlecodelabs/activity_transitionapi-codelab#16]
Underneath the third code snippet, it says

`Here we as if activity recognition is approved. If it is and activity recognition is already enabled, we disable it. Otherwise, we enable it.`

Shouldn't it be?

`Here we (check/verify) if activity recognition is approved. If it is and activity recognition is already enabled, we disable it. Otherwise, we enable it.`

**Comment by osuleymanova** [comment]
@lorduriel 
Thank you for reaching out to us. The issue is fixed and will be published soon.
