### ISSUE TITLE
Lab: Application Performance Management (APM) with Stackdriver

### ISSUE THREAD

**Issue by phluks** [googlecodelabs/activity_transitionapi-codelab#2]
That lab does not seem to have its own repo. I'd be delighted if you could forward to the responsible party. Anyhow it fails. It seems that some images are missing. See screenshot.
![screenshot from 2019-02-07 14-19-46](https://user-images.githubusercontent.com/763249/52414872-be4b6400-2ae5-11e9-8559-a280100b79a9.png)

**Comment by codingjeremy** [comment]
I rewrote the code so it should be working now. PTAL and reopen if it doesn't work.
