### ISSUE TITLE
Wrong link to github repository

### ISSUE THREAD

**Issue by gaglileo** [googlecodelabs/activity_transitionapi-codelab#5]
The link to repository download is not working, as it is 
[https://github.com/googlecodelabs/activity_transitionapi-codelab/BasicActivityTransitionsCodelab.zip](url)

and it should be:
[https://github.com/googlecodelabs/activity_transitionapi-codelab/blob/master/BasicActivityTransitionsCodelab.zip](url)

**Comment by elirehema** [comment]
Download repository as a zipped folder and unzip

**Comment by codingjeremy** [comment]
I rewrote the codelab and fixed all links. PTAL and reopen if you see the same problem. Thanks!
