### ISSUE TITLE
Link to BasicActivityTransitionsCodelab.zip returns not found.

### ISSUE THREAD

**Issue by chrystianv** [googlecodelabs/activity_transitionapi-codelab#6]
Perhaps the codelab should link to where the repository is, instead of directly to the zip file:

https://github.com/googlecodelabs/activity_transitionapi-codelab

**Comment by codingjeremy** [comment]
That latest PR removes the zip file and re-inserts the code (along with quite a few fixes). Please take a look and thanks for reporting the issue!
