### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by zawawimanja** [googlecodelabs/activity_transitionapi-codelab#8]
I am using Android 9  Xiaomi but it is not working.

**Comment by zawawimanja** [comment]
I just tested on Android 5  Samsung and it is working. Dont know if the problem related to the android version.

**Comment by darrylyip** [comment]
I just tested on nokia 6/android 10 and nexus 5x/android 7 as well and don't see any activity transitions.

**Comment by darrylyip** [comment]
Got it working.  Had to ditch LocalBroadcastManager and just call registerReceiver in onStart and unregisterReceiver in onStop.

**Comment by zawawimanja** [comment]
> Got it working. Had to ditch LocalBroadcastManager and just call registerReceiver in onStart and unregisterReceiver in onStop.

I already use this  code but nothing works.

 @Override
    protected void onStop() {

        unregisterReceiver(broadcastReceiver);
        super.onStop();
    }

    @Override
    protected void onStart() {
        super.onStart();
        LocalBroadcastManager.getInstance(this).registerReceiver(broadcastReceiver,
                new IntentFilter(Constants.BROADCAST_DETECTED_ACTIVITY));

    }

**Comment by RonLek** [comment]
@darrylyip can you please explain how you got it working?

**Comment by darrylyip** [comment]
Hi please check out my test project here: https://github.com/darrylyip/ActivityTransitionAPIExample.  hopefully this helps.  The transition api takes about 1-2 minutes before it gives you any transitions.  The example uses ActivityUpdates as well and you can see the difference in responsiveness between the two.

**Comment by RonLek** [comment]
@darrylyip it worked! Thanks.

**Comment by zawawimanja** [comment]
I dont know what is happening. I noticed that it takes time to appear. Sometimes it will disappear and sometimes appear.

**Comment by thelou1s** [comment]
@darrylyip it worked! Thanks. 
BTW, What's wrong with google's demo code? What changed in you code? Thanks again.
